/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Sheet = IDL.Record({
  'height' : IDL.Float64,
  'sheetLabel' : IDL.Text,
  'quantity' : IDL.Nat,
  'width' : IDL.Float64,
});
export const Piece = IDL.Record({
  'height' : IDL.Float64,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'width' : IDL.Float64,
});
export const Time = IDL.Int;
export const Project = IDL.Record({
  'id' : IDL.Text,
  'sheets' : IDL.Vec(Sheet),
  'name' : IDL.Text,
  'createdAt' : Time,
  'pieces' : IDL.Vec(Piece),
  'updatedAt' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearUserData' : IDL.Func([], [], []),
  'countProjects' : IDL.Func([], [IDL.Nat], ['query']),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Vec(Sheet), IDL.Vec(Piece)],
      [IDL.Text],
      [],
    ),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllProjectsAdmin' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Project))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProjectsAdmin' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'projectExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(Sheet), IDL.Vec(Piece)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Sheet = IDL.Record({
    'height' : IDL.Float64,
    'sheetLabel' : IDL.Text,
    'quantity' : IDL.Nat,
    'width' : IDL.Float64,
  });
  const Piece = IDL.Record({
    'height' : IDL.Float64,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'width' : IDL.Float64,
  });
  const Time = IDL.Int;
  const Project = IDL.Record({
    'id' : IDL.Text,
    'sheets' : IDL.Vec(Sheet),
    'name' : IDL.Text,
    'createdAt' : Time,
    'pieces' : IDL.Vec(Piece),
    'updatedAt' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearUserData' : IDL.Func([], [], []),
    'countProjects' : IDL.Func([], [IDL.Nat], ['query']),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Vec(Sheet), IDL.Vec(Piece)],
        [IDL.Text],
        [],
      ),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllProjectsAdmin' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Project))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProjectsAdmin' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'projectExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(Sheet), IDL.Vec(Piece)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };