/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Piece {
  'height' : number,
  'description' : string,
  'quantity' : bigint,
  'width' : number,
}
export interface Project {
  'id' : string,
  'sheets' : Array<Sheet>,
  'name' : string,
  'createdAt' : Time,
  'pieces' : Array<Piece>,
  'updatedAt' : Time,
}
export interface Sheet {
  'height' : number,
  'sheetLabel' : string,
  'quantity' : bigint,
  'width' : number,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearUserData' : ActorMethod<[], undefined>,
  'countProjects' : ActorMethod<[], bigint>,
  'createProject' : ActorMethod<[string, Array<Sheet>, Array<Piece>], string>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllProjectsAdmin' : ActorMethod<[], Array<[Principal, Project]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProject' : ActorMethod<[string], Project>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProjectsAdmin' : ActorMethod<[Principal], Array<Project>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'projectExists' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProject' : ActorMethod<
    [string, string, Array<Sheet>, Array<Piece>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];